# Generated by Django 6.0.2 on 2026-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0002_post_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='case_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
