# Generated by Django 6.0.2 on 2026-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0003_post_case_id_post_latitude_post_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='municipal_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
