# Generated by Django 6.0.2 on 2026-03-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0004_post_municipal_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='action_timeline_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='is_petition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('adopted and pending', 'Adopted and Pending'), ('adopted and solved', 'Adopted and Solved')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='civic_pulse.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
