# Generated by Django 6.0.2 on 2026-03-15 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0005_post_action_timeline_days_post_is_petition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
