# Generated by Django 6.0.2 on 2026-03-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0007_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coordinator_name',
        ),
    ]
