# Generated by Django 6.0.2 on 2026-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0008_remove_user_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
